// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFnTQ5x0difPcxFQt-hkLbDxxeMZdzeXM',
    appId: '1:444216824782:web:c5923a94982195b543119f',
    messagingSenderId: '444216824782',
    projectId: 'archie-bell-notif-system',
    authDomain: 'archie-bell-notif-system.firebaseapp.com',
    storageBucket: 'archie-bell-notif-system.firebasestorage.app',
    measurementId: 'G-EBPYCGLGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMhhPwLt5TKOLE0OT5J3W9tVGs7DhmzBM',
    appId: '1:444216824782:android:1602c61e5e26310943119f',
    messagingSenderId: '444216824782',
    projectId: 'archie-bell-notif-system',
    storageBucket: 'archie-bell-notif-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZxVCpHdccQzVS7jFnEsoyKnAs7fnbpY',
    appId: '1:444216824782:ios:3b9bd6091da75f4a43119f',
    messagingSenderId: '444216824782',
    projectId: 'archie-bell-notif-system',
    storageBucket: 'archie-bell-notif-system.firebasestorage.app',
    iosBundleId: 'com.archieBell.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZxVCpHdccQzVS7jFnEsoyKnAs7fnbpY',
    appId: '1:444216824782:ios:3b9bd6091da75f4a43119f',
    messagingSenderId: '444216824782',
    projectId: 'archie-bell-notif-system',
    storageBucket: 'archie-bell-notif-system.firebasestorage.app',
    iosBundleId: 'com.archieBell.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFnTQ5x0difPcxFQt-hkLbDxxeMZdzeXM',
    appId: '1:444216824782:web:4181001ed36cd19e43119f',
    messagingSenderId: '444216824782',
    projectId: 'archie-bell-notif-system',
    authDomain: 'archie-bell-notif-system.firebaseapp.com',
    storageBucket: 'archie-bell-notif-system.firebasestorage.app',
    measurementId: 'G-GFFJKKRZ15',
  );
}
